# Generated by Django 5.2.12 on 2026-03-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "template_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "target_segment",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("opened", models.PositiveIntegerField(default=0)),
                ("clicked", models.PositiveIntegerField(default=0)),
                ("bounced", models.PositiveIntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_campaigns",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "email_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brevo_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "template_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("subject", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="queued",
                        max_length=15,
                    ),
                ),
                (
                    "bounce_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("bounce_reason", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="communications.emailcampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("newsletter", "Newsletter"),
                            ("donation_receipt", "Donation Receipt"),
                            ("event", "Event"),
                            ("pastoral", "Pastoral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("consented", models.BooleanField(default=False)),
                (
                    "consent_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_consents",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_consents",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "email_consent",
                "unique_together": {("tenant", "member", "communication_type")},
            },
        ),
    ]
