# Generated by Django 5.2.12 on 2026-03-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("church_name", models.CharField(default="My Church", max_length=200)),
                (
                    "church_logo",
                    models.ImageField(blank=True, null=True, upload_to="church/"),
                ),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("church_address", models.CharField(blank=True, max_length=200)),
                ("church_city", models.CharField(blank=True, max_length=100)),
                ("church_state", models.CharField(blank=True, max_length=100)),
                ("church_zip", models.CharField(blank=True, max_length=20)),
                ("church_country", models.CharField(default="USA", max_length=100)),
                ("church_phone", models.CharField(blank=True, max_length=50)),
                ("church_email", models.EmailField(blank=True, max_length=254)),
                ("church_website", models.URLField(blank=True)),
                ("ein_tax_id", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=50),
                ),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=20)),
                ("brevo_api_key", models.CharField(blank=True, max_length=200)),
                ("default_from_email", models.EmailField(blank=True, max_length=254)),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                (
                    "thankyou_email_subject_template",
                    models.CharField(
                        default="{church_name} — Thank you for your generous contribution",
                        max_length=200,
                    ),
                ),
                (
                    "thankyou_email_intro_text",
                    models.TextField(
                        default="We are grateful for your generous contribution to our church."
                    ),
                ),
                ("email_image_url", models.URLField(blank=True)),
                ("turnstile_site_key", models.CharField(blank=True, max_length=100)),
                ("turnstile_secret_key", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Church Settings",
                "verbose_name_plural": "Church Settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("promote", "Promote"),
                            ("revoke", "Revoke"),
                            ("export", "Export"),
                            ("settings_change", "Settings Change"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("member", "Member"),
                            ("contribution", "Contribution"),
                            ("user", "User"),
                            ("family", "Family"),
                            ("settings", "Settings"),
                            ("category", "Category"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
